# Generated by Django 2.2 on 2021-11-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '이미 있는 제목이네요!'}, max_length=50, unique=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('up_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Class')),
            ],
        ),
    ]
