# Generated by Django 2.2 on 2021-11-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='up_class',
            new_name='upclass',
        ),
    ]
