# Generated by Django 2.2 on 2021-11-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211124_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uplesson',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='posts.Lesson'),
            preserve_default=False,
        ),
    ]
