# Generated by Django 2.2 on 2021-11-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211125_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Class'),
        ),
    ]
