# Generated by Django 2.2 on 2021-11-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211126_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(error_messages={'unique': '이미 있는 클레스이군요!'}, max_length=50, unique=True),
        ),
    ]
