# Generated by Django 2.2 on 2021-11-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211127_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='dt_modified',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='dt_modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dt_modified',
        ),
    ]
